# Root Netlify configuration for monorepo
[build]
  # Set base to the frontend folder
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
